include ./theme.conf
background_opacity 0.8
background_blur 1
confirm_os_window_close 0
confirm_close=no
font_family Hack Nerd Font Mono
# tabs
tab_bar_style powerline
# Active tab colors
active_tab_foreground   #000000
active_tab_background   #87CEFA  
active_tab_font_style   bold-italic

# Inactive tab colors
inactive_tab_foreground #444444
inactive_tab_background #B0C4DE
inactive_tab_font_style normal
# Shell
shell zsh
